"""FEAT-005 test fixtures — deterministic, offline LLM mocking + PDF text.

The backend test suite must run fully offline (no real LLM/network call). This
module provides:

- ``SYNTHETIC_PDF_TEXT`` — the text of the shipped
  ``ClaimBlitz_Synthetic_Medical_Claim_Report.pdf``. It was generated by
  extracting the real binary with PyMuPDF (``fitz``) during implementation and
  committed verbatim as a string literal (design §15 / review finding #5), so
  the deterministic tests do not depend on the PDF binary yet cannot silently
  drift from it. ``test_billing_lines_sum_to_total`` guards transcription by
  asserting the seven billing lines still sum to ``48760.00``.

- ``LLMMock`` + the ``golden_llm_scripts`` dispatcher — a monkeypatch of
  ``AsyncLLMClient.call_json`` keyed by each agent's unique ``system_prompt``
  marker string (design §15). The real pipeline, mappers, status/billing math,
  jurisdiction inference and Judge guards all execute; only the LLM call is
  canned. The dispatcher raises ``AssertionError`` if an invoked prompt has no
  scripted response, so a missing script fails loudly instead of silently
  defaulting (a Scanner default of ``processable: false`` would otherwise abort
  every integration test before OCR — review finding #9).

Tests that need scripted LLM output ``monkeypatch`` ``call_json`` with an
``LLMMock`` instance; this overrides the autouse ``offline_llm`` fixture
declared in ``backend/conftest.py``.
"""

from __future__ import annotations

import json
from typing import Any, Callable

import pytest

from agentcore.llm import AsyncLLMClient, LLMResult

# The synthetic-PDF text fixture, generated from the shipped binary (never
# hand-transcribed). Kept in its own module so the big string literal does not
# clutter the fixtures.
from tests._pdf_fixture import SYNTHETIC_PDF_TEXT  # noqa: F401

__all__ = [
    "SYNTHETIC_PDF_TEXT",
    "LLMMock",
    "golden_llm_scripts",
    "SEVEN_BILLING_LINES",
    "EXPECTED_BILLING_TOTAL",
]


# ---------------------------------------------------------------------------
# Agent prompt markers (design §15). Each agent's system_prompt contains a
# unique, stable marker substring; the dispatcher keys on it.
# ---------------------------------------------------------------------------

AGENT_MARKERS: dict[str, str] = {
    "scanner": "Scanner Agent",
    "ocr": "OCR/Extraction Agent",
    "validator": "Validator Agent",
    "clinical": "Medical Expert Agent",
    "policy": "Policy Expert Agent",
    "fraud": "Fraud Detection Agent",
    "risk": "Risk Assessment Agent",
    "judge": "Judge Agent",
    "communication": "Communication Agent",
}


# ---------------------------------------------------------------------------
# Billing ground-truth (design §1 / §15). The seven itemized hospital-bill
# lines on page 3 of the synthetic PDF.
# ---------------------------------------------------------------------------

SEVEN_BILLING_LINES: list[tuple[str, float]] = [
    ("Room & nursing charges", 18000.00),
    ("Doctor / professional charges", 8500.00),
    ("Laboratory investigations", 5460.00),
    ("Radiology / imaging", 2800.00),
    ("Pharmacy / medicines", 7250.00),
    ("Consumables", 3750.00),
    ("Other hospital services", 3000.00),
]
EXPECTED_BILLING_TOTAL = 48760.00


# ---------------------------------------------------------------------------
# LLM mock dispatcher
# ---------------------------------------------------------------------------


class LLMMock:
    """A marker-keyed, offline replacement for ``AsyncLLMClient.call_json``.

    ``scripts`` maps a prompt-marker key (one of :data:`AGENT_MARKERS` keys,
    e.g. ``"scanner"``) to either:
      - a ``dict`` returned as the parsed LLM payload, or
      - a callable ``(prompt: str) -> dict`` for prompt-dependent responses, or
      - an ``Exception`` **instance** (or a callable returning one) that is
        raised instead — used to simulate a provider outage (TC10).

    The dispatcher resolves the marker from the prompt text. If no marker
    matches, or the matched marker has no script, it raises ``AssertionError``
    so a missing script fails loudly (design §15).
    """

    def __init__(self, scripts: dict[str, Any]) -> None:
        self.scripts = scripts
        # Record of (marker_key, max_tokens) for assertions (e.g. OCR invoked
        # exactly once per run — finding #10).
        self.calls: list[str] = []

    def _marker_for(self, prompt: str) -> str:
        matched = [key for key, marker in AGENT_MARKERS.items() if marker in prompt]
        assert matched, (
            "LLMMock: prompt did not contain any known agent marker. "
            f"First 160 chars: {prompt[:160]!r}"
        )
        assert len(matched) == 1, (
            f"LLMMock: prompt matched multiple agent markers {matched}; "
            "markers must be unique."
        )
        return matched[0]

    async def call_json(self, prompt: str, *, max_tokens: int = 1200) -> LLMResult:
        key = self._marker_for(prompt)
        self.calls.append(key)
        assert key in self.scripts, (
            f"LLMMock: no scripted response for agent {key!r} "
            f"(marker {AGENT_MARKERS[key]!r}). Add it to the script."
        )
        payload = self.scripts[key]
        if callable(payload) and not isinstance(payload, dict):
            payload = payload(prompt)
        if isinstance(payload, BaseException):
            raise payload
        if isinstance(payload, type) and issubclass(payload, BaseException):
            raise payload()
        assert isinstance(payload, dict), (
            f"LLMMock: script for {key!r} must resolve to a dict, got {type(payload)}"
        )
        return LLMResult(
            parsed=dict(payload),
            raw_text=json.dumps(payload),
            provider="mock",
            model="mock-llm",
            latency_ms=0.0,
        )

    def install(self, monkeypatch: pytest.MonkeyPatch) -> "LLMMock":
        """Monkeypatch ``AsyncLLMClient.call_json`` with this mock."""
        monkeypatch.setattr(AsyncLLMClient, "call_json", self.call_json, raising=True)
        return self


# ---------------------------------------------------------------------------
# The golden-path script (full REVIEW outcome for the synthetic PDF).
# ---------------------------------------------------------------------------


def _ocr_payload() -> dict[str, Any]:
    """A full, valid OCR extraction payload for the synthetic PDF.

    Mirrors the ground-truth facts (design §1): Aarav Mehta, pneumonia, J18.9,
    the seven billing lines summing to 48760, policy/identity documents 'Not
    included', INR. Each scalar is a {value, page, confidence} cell per the OCR
    extraction schema; code (not the LLM) assigns status/billing/jurisdiction.
    """

    def cell(value: Any, page: int | None = 1, confidence: float = 0.95) -> dict[str, Any]:
        return {"value": value, "page": page, "confidence": confidence}

    return {
        "claim_info": {
            "claim_id": cell("CB-DEMO-2026-10482", page=3),
            "claim_type": cell("inpatient hospitalization", page=3),
            "submission_date": cell(None),
            "status": cell("For adjudication", page=3),
        },
        "patient": {
            "name": cell("Aarav Mehta"),
            "dob": cell("12 February 1992"),
            "age": cell("34"),
            "gender": cell("Male"),
            "patient_id": cell("RVH-DEM-260918"),
            "address": cell("Pune, Maharashtra"),
            "phone": cell(None),
            "email": cell(None),
            "blood_group": cell("B Positive"),
            "insurance_id": cell(None),
        },
        "policy": {
            # Claim-sheet identifiers are allowed to be EXTRACTED (page 3).
            "insurer_name": cell(None),
            "policy_number": cell("DEMO-POL-784215", page=3),
            "policyholder_name": cell("Aarav Mehta", page=3),
            # Coverage terms are NOT present (no policy document); the OCR
            # mapper keeps these MISSING regardless of what the LLM reports.
            "start_date": cell(None),
            "end_date": cell(None),
            "plan_name": cell(None),
            "coverage_type": cell(None),
            "sum_insured": cell(None),
            "remaining_sum_insured": cell(None),
            "room_rent_limit": cell(None),
            "copay": cell(None),
            "deductible": cell(None),
            "waiting_period": cell(None),
            "exclusions": cell(None),
        },
        "provider": {
            "hospital_name": cell("Riverview Care Hospital & Trauma Centre"),
            "address": cell("42 Lakeview Avenue, Pune, Maharashtra 411038"),
            "registration_number": cell(None),
            "provider_id": cell(None),
            "npi": cell(None),  # India — NPI is a US concept, stays MISSING
            "doctor_name": cell("Dr. Neha Kulkarni"),
            "doctor_registration_number": cell(None),
            "specialization": cell("Internal Medicine"),
            "department": cell("Internal Medicine"),
        },
        "hospitalization": {
            "admission_date": cell("18 September 2026"),
            "admission_time": cell(None),
            "discharge_date": cell("21 September 2026"),
            "discharge_time": cell(None),
            "admission_type": cell("Emergency → Inpatient", page=3),
            "ward": cell("Medical Ward"),
            "bed": cell("3B-17"),
            "icu_stay": cell(None),
            "length_of_stay": cell("3 nights / 4 calendar days", page=3),
        },
        "clinical": {
            "chief_complaint": cell(
                "2-day history of fever, productive cough, right-sided chest discomfort"
            ),
            "symptoms": cell("fever, productive cough, shortness of breath"),
            "findings": cell("coarse crackles over the right lower lung field"),
            "primary_diagnosis": cell(
                "Community-acquired pneumonia, right lower lobe"
            ),
            "secondary_diagnoses": cell(None),
            "diagnosis_codes": {
                "value": ["J18.9 — Pneumonia, unspecified organism"],
                "page": 1,
                "confidence": 0.95,
            },
            "history": cell(None),
            "allergies": cell(None),
        },
        "procedures": [],
        "investigations": [
            {
                "name": cell("Hemoglobin"),
                "date": cell(None),
                "result": cell("13.8 g/dL"),
                "reference_range": cell("12.0-17.0 g/dL"),
                "amount": cell(None),
            },
            {
                "name": cell("Chest X-ray"),
                "date": cell(None),
                "result": cell("Right lower-zone infiltrate"),
                "reference_range": cell(None),
                "amount": cell(None),
            },
        ],
        "medications": [
            {
                "name": cell("Amoxicillin/clavulanate 625 mg"),
                "dosage": cell("625 mg"),
                "frequency": cell("three times daily"),
                "route": cell("oral"),
                "start_date": cell(None),
                "end_date": cell(None),
                "amount": cell(None),
            }
        ],
        "billing": {
            "line_items": [
                {
                    "category": cell(name, page=3),
                    "description": cell(name, page=3),
                    "amount": cell(amount, page=3),
                }
                for name, amount in SEVEN_BILLING_LINES
            ],
            "submitted_total": cell(EXPECTED_BILLING_TOTAL, page=3),
            "currency": cell("INR", page=3),
        },
        "supporting_documents": {
            "discharge_summary": {"present": True, "page": 1},
            "hospital_bill": {"present": True, "page": 3},
            "lab_reports": {"present": True, "page": 3},
            "imaging_reports": {"present": True, "page": 3},
            "prescriptions": {"present": True, "page": 4},
            "medical_records": {"present": True, "page": 1},
            # 'Not included in this demo packet' -> absent.
            "policy_document": {"present": False, "page": None},
            "identity_document": {"present": False, "page": None},
        },
        "confidence": 0.9,
        "notes": "Synthetic demo document.",
    }


def golden_llm_scripts(**overrides: Any) -> dict[str, Any]:
    """Default scripts producing the golden REVIEW path for the synthetic PDF.

    All analysts return non-blocking/consistent output; the Judge scripts an
    ``approve`` that the code guard overrides to REVIEW because the Risk agent
    publishes ``policy_document_missing`` + ``identity_document_missing``
    blocking conditions (no policy/identity doc). ``overrides`` replaces a
    per-marker script (e.g. ``policy=SomeException`` for TC10).
    """
    scripts: dict[str, Any] = {
        "scanner": {
            "processable": True,
            "document_type": "claim_form",
            "quality": "high",
            "confidence": 0.9,
            "reason": "valid claim form",
        },
        "ocr": _ocr_payload(),
        "validator": {
            "findings": [],
            "confidence": 0.9,
            "summary": "Structural checks complete.",
        },
        "clinical": {
            "verdict": "approve",
            "confidence": 0.9,
            "reasoning": "Diagnosis is consistent with the documented findings.",
            "checks": [
                {
                    "check": "dx_doc",
                    "result": "consistent",
                    "evidence": "coarse crackles; right lower-zone infiltrate",
                    "note": "Pneumonia supported by exam and imaging.",
                }
            ],
        },
        # Policy is short-circuited by code (no policy document) BEFORE the LLM
        # is called, so this script is normally not consulted. It is provided
        # so an unexpected invocation does not trip the AssertionError.
        "policy": {
            "coverage_status": "INSUFFICIENT_EVIDENCE",
            "coverage_evidence": [],
            "relevant_clause": None,
            "missing_policy_info": ["sum_insured", "exclusions"],
            "confidence": 0.6,
            "reasoning": "No policy document present.",
        },
        "fraud": {
            "fraud_indicators": [],
            "overall_fraud_assessment": "No concrete fraud signals.",
            "confidence": 0.85,
        },
        "risk": {
            "reasoning": "Documentation gaps (no policy/identity document) drive review.",
            "confidence": 0.8,
            "notes": [],
        },
        "judge": {
            "verdict": "approve",
            "confidence": 0.9,
            "reasoning": "Analysts broadly consistent.",
            "dissenting_agents": [],
            "requires_human_review": False,
        },
        "communication": {
            "email_draft": "Additional documentation is required before the claim can proceed.",
            "sms_draft": "Your claim is under review; more documents are needed.",
            "internal_note": "Routed to review: policy/identity docs missing.",
            "tone": "professional",
            "confidence": 0.9,
        },
    }
    scripts.update(overrides)
    return scripts


# ---------------------------------------------------------------------------
# pytest fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def llm_scripts() -> Callable[..., dict[str, Any]]:
    """Expose the golden-path script factory to tests."""
    return golden_llm_scripts


@pytest.fixture
def golden_llm(monkeypatch: pytest.MonkeyPatch) -> LLMMock:
    """Install the golden-path LLM mock; return it for per-test assertions."""
    return LLMMock(golden_llm_scripts()).install(monkeypatch)
